API:
  url: "https://api.football-data.org/v4/"
  token: "12abfbaacdab48bc8948ed6061925e1f"
  account: "testing.data999@gmail.com"
  timeout: 30 # seconds
  retry_attempts: 3

Directories:
  output_dir: data
  log_dir: logs
  test_dir: tests
  cache_dir: cache

Optimization:
  enable_caching: True
  cache_ttl: 86400  # Cache time-to-live in seconds (defaults to 1 day)
  workers: 4        # Number of parallel workers for data processing
  batch_size: 1000  # Number of records to process in each batch

Reporting:
  data_quality_report: True
  add_data_lineage': True